# Site settings
title: Mark Hall
description: >
  My personal blog, usually about iOS development, sometimes its not.

baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://markhall.co" # the base hostname & protocol for your site

author:
  fullname: Mark Hall
  github: golfguru1
  twitter: softieeng
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown

source: blog
